version: '3'
services:
  web:
    build: .
    env_file: .env
    working_dir: /death-star-server
    volumes:
      - './:/death-star-server'
    command: bash -c 'bin/rails s -p 3000 -b "0.0.0.0"'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    links:
      - postgres:postgres
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  postgres_data:
    driver: local
